### ISSUE TITLE
What-if Analysis doesn't work if Input and result is on different sheet

### ISSUE THREAD

**Issue by gmadd66** [sajacy/google-sheets-what-if-analysis#10]
Hi

If I have a model which has an input at Sheet1A2 and gets a result Sheet1A5. I cant seem to run the scenario analyses results on a second sheet say Sheet2, which references the Sheet1 inputs and results.

Regards

**Comment by timhsanchez1** [comment]
I also have the same issue. I'd like to reference row and column values in a separate sheet, (e.g. "P&L!B16"), but when I do that, it gives me the same output value in every cell of the table.

Thanks,
Tim

**Comment by sajacy** [comment]
Resolved in #6 

Thanks for your input! (sorry this has been neglected)
