### ISSUE TITLE
suggestion to allow one input and multiple outputs

### ISSUE THREAD

**Issue by axrand** [sajacy/google-sheets-what-if-analysis#11]
I very often use WhatIf analysis to check several outputs (depending on one input).
First column contains input, then all other columns contain several outputs from the same model and the same one input from the first column. Just like in excel, when you only define column input - the top row contains links to different outputs.
In current edition there is either one input - one output, OR two inputs - one output.

**Comment by sajacy** [comment]
Ah interesting - thanks for the suggestion, this makes a ton of sense.  Will prioritize this.

**Comment by sajacy** [comment]
#17 Implemented, the new feature is triggered when multiple columns are selected but the row input blank.
