### ISSUE TITLE
Unavailable for install

### ISSUE THREAD

**Issue by LiranBri** [sajacy/google-sheets-what-if-analysis#15]
Hello,
When I try to install it through G Suite Marketplace, I see the following messages:

**_Unavailable for install
Admin-install only_**

Am I missing something?

**Comment by yzAlvin** [comment]
To get around this, you can follow the manual installation steps in the README.md

**Comment by sajacy** [comment]
I've updated the Marketplace configuration to allow individual install.  Thanks for pointing this out!
