### ISSUE TITLE
Trust

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [sajacy/google-sheets-what-if-analysis#3]
Dear Jeffrey,

a company in Berlin/Germany would love to use your what-if add-on  for Google Spreadsheets.

As your add-on needs full-access to the spreadsheets we have to clarify that you are not a data-broker or agent owned by some foreign gov. ,-)

Might I have the handle to your LinkedIn Profile to follow up? Best, HHvA ,-)

**Comment by sajacy** [comment]
Sorry for the very late response.  If it's still relevant, [this is my LinkedIn](https://www.linkedin.com/in/jeffreyyang/)
