### ISSUE TITLE
Error in a simple what-if table

### ISSUE THREAD

**Issue by Alex-agent** [sajacy/google-sheets-what-if-analysis#4]
Hi, 

I got an error message "TTypeError: Cannot set property "DataTable_B7C11" of null to "[object Object]"." when I create a standard what-if data table with one variable. 
Pls see example (Error 1 tab): https://goo.gl/Z4Wgw2

**Comment by sajacy** [comment]
This is usually a problem caused by not being logged in, or not authorizing the add-on to modify the sheet.  Duplicate of #9
