### ISSUE TITLE
Input 

### ISSUE THREAD

**Issue by Alex-agent** [sajacy/google-sheets-what-if-analysis#5]
Hi

If Input cell contains a formula or a reference to another cell, after creation a what-if data table the input cell formula/reference is replaced with a hard value. 

Thanks

**Comment by redbar0n** [comment]
Yes, so the input cell needs to be that cell you called "another cell". Then the formula/reference cell will not be overwritten, and be updated automatically like it should.

@sajacy This issue can be closed.
