### ISSUE TITLE
Error at end of analysis

### ISSUE THREAD

**Issue by jayc481** [sajacy/google-sheets-what-if-analysis#9]
Get the following error at the end of successfully creating a new data table

TypeError: Cannot set property "DataTable_P12Z19" of null to "[object Object]".

Then, when trying to refresh, get the associated error:

TypeError: Cannot read property "DataTable_P12Z19" from null.

**Comment by sajacy** [comment]
This is usually caused by trying to access a sheet without being logged in.

**Comment by sajacy** [comment]
Should be fixed in #16 .  If not, and this happens again, please open a new issue and note if the document is owned by you, and if you are logged in, as well as the error message.  Thanks!
